[2024-10-15T03:45:32.500+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T03:45:32.527+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_Airflow__clean_log_rolling.clean_scheduler_logs scheduled__2024-10-14T00:35:00+00:00 [queued]>
[2024-10-15T03:45:32.540+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_Airflow__clean_log_rolling.clean_scheduler_logs scheduled__2024-10-14T00:35:00+00:00 [queued]>
[2024-10-15T03:45:32.542+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-15T03:45:32.566+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): clean_scheduler_logs> on 2024-10-14 00:35:00+00:00
[2024-10-15T03:45:32.578+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=971) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-15T03:45:32.576+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'DAG_Airflow__clean_log_rolling', 'clean_scheduler_logs', 'scheduled__2024-10-14T00:35:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/DAG_Airflow_Clean_Logs.py', '--cfg-path', '/tmp/tmp5lp4if2o']
[2024-10-15T03:45:32.579+0000] {standard_task_runner.py:72} INFO - Started process 972 to run task
[2024-10-15T03:45:32.580+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask clean_scheduler_logs
[2024-10-15T03:45:32.618+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-15T03:45:32.673+0000] {task_command.py:467} INFO - Running <TaskInstance: DAG_Airflow__clean_log_rolling.clean_scheduler_logs scheduled__2024-10-14T00:35:00+00:00 [running]> on host c8eca7e310e3
[2024-10-15T03:45:32.678+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-15T03:45:32.950+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='de@***' AIRFLOW_CTX_DAG_ID='DAG_Airflow__clean_log_rolling' AIRFLOW_CTX_TASK_ID='clean_scheduler_logs' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T00:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T00:35:00+00:00'
[2024-10-15T03:45:33.751+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T03:45:33.835+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-15T03:45:33.838+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm -rf /root/***/logs/scheduler/2024-08-24']
[2024-10-15T03:45:33.851+0000] {subprocess.py:86} INFO - Output:
[2024-10-15T03:45:33.990+0000] {subprocess.py:93} INFO - rm: cannot remove '/root/***/logs/scheduler/2024-08-24': Permission denied
[2024-10-15T03:45:33.995+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-15T03:45:34.029+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-15T03:45:34.056+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=DAG_Airflow__clean_log_rolling, task_id=clean_scheduler_logs, run_id=scheduled__2024-10-14T00:35:00+00:00, execution_date=20241014T003500, start_date=20241015T034532, end_date=20241015T034534
[2024-10-15T03:45:34.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T03:45:34.133+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task clean_scheduler_logs (Bash command failed. The command returned a non-zero exit code 1.; 972)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-15T03:45:34.165+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-15T03:45:34.245+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T03:45:34.253+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
